@startuml
skinparam linetype polyline

' Pattern comments that will be processed by GenUML:
'!gen_java com.enth.ecomusic.model.entity.User
class User {
  com.enth.ecomusic.model.entity
  --
  - userId: int
  - firstName: String
  - lastName: String
  - username: String
  - bio: String
  - email: String
  - password: String
  - roleId: int
  - imageUrl: String
  - createdAt: LocalDateTime
  - role: Role
  --
  + User(): 
  + User(int, String, String, String, String, String, String, int, String, LocalDateTime): 
  + User(String, String, String, String, String, String, int, String): 
  + User(String, String, String, String, String, String, int): 
  + User(String, String, String, String, String, String): 
  + getUserId(): int
  + setUserId(int): void
  + getFirstName(): String
  + setFirstName(String): void
  + getLastName(): String
  + setLastName(String): void
  + getUsername(): String
  + setUsername(String): void
  + getBio(): String
  + setBio(String): void
  + getEmail(): String
  + setEmail(String): void
  + getPassword(): String
  + setPassword(String): void
  + getRoleId(): int
  + setRoleId(int): void
  + getImageUrl(): String
  + setImageUrl(String): void
  + getCreatedAt(): LocalDateTime
  + setCreatedAt(LocalDateTime): void
  + getRole(): Role
  + setRole(Role): void
}


@enduml
