@startuml
skinparam linetype polyline

' Pattern comments that will be processed by GenUML:
package "entity" {
    '!gen_java com.enth.ecomusic.model.entity.User
    '!gen_java com.enth.ecomusic.model.entity.Genre
    '!gen_java com.enth.ecomusic.model.entity.Mood
    '!gen_java com.enth.ecomusic.model.entity.Music
    '!gen_java com.enth.ecomusic.model.entity.PlayHistory
    '!gen_java com.enth.ecomusic.model.entity.Playlist
    '!gen_java com.enth.ecomusic.model.entity.PlaylistMusic
    '!gen_java com.enth.ecomusic.model.entity.Role
    '!gen_java com.enth.ecomusic.model.entity.SubscriptionPlan
    '!gen_java com.enth.ecomusic.model.entity.UserSubscription
}

package "dao" {
    '!gen_java com.enth.ecomusic.model.dao.GenreDAO
    '!gen_java com.enth.ecomusic.model.dao.LikeDAO
    '!gen_java com.enth.ecomusic.model.dao.MoodDAO
    '!gen_java com.enth.ecomusic.model.dao.MusicDAO
    '!gen_java com.enth.ecomusic.model.dao.PlaylistDAO
    '!gen_java com.enth.ecomusic.model.dao.PlaylistMusicDAO
    '!gen_java com.enth.ecomusic.model.dao.PlayHistoryDAO
    '!gen_java com.enth.ecomusic.model.dao.RoleDAO
    '!gen_java com.enth.ecomusic.model.dao.SubscriptionDAO
    '!gen_java com.enth.ecomusic.model.dao.SubscriptionPlanDAO
}

package "service" {
    '!gen_java com.enth.ecomusic.service.UserService
    '!gen_java com.enth.ecomusic.service.GenreCacheService
    '!gen_java com.enth.ecomusic.service.MoodCacheService
    '!gen_java com.enth.ecomusic.service.RoleCacheService
    '!gen_java com.enth.ecomusic.service.LikeService
    '!gen_java com.enth.ecomusic.service.MusicService
    '!gen_java com.enth.ecomusic.service.PlaylistService
    '!gen_java com.enth.ecomusic.service.PlayHistoryService
    '!gen_java com.enth.ecomusic.service.StripeService
    '!gen_java com.enth.ecomusic.service.SubscriptionService
}

package "dto" {
    '!gen_java com.enth.ecomusic.model.dto.LikeDTO
    '!gen_java com.enth.ecomusic.model.dto.MusicDTO
    '!gen_java com.enth.ecomusic.model.dto.MusicDetailDTO
    '!gen_java com.enth.ecomusic.model.dto.PlayHistoryDTO
    '!gen_java com.enth.ecomusic.model.dto.PlaylistDTO
    '!gen_java com.enth.ecomusic.model.dto.PlaylistMusicDTO
    '!gen_java com.enth.ecomusic.model.dto.StreamRangeDTO
    '!gen_java com.enth.ecomusic.model.dto.SubscriptionDTO
    '!gen_java com.enth.ecomusic.model.dto.SubscriptionPlanDTO
    '!gen_java com.enth.ecomusic.model.dto.UserDTO
}

package "enum" {
    '!gen_java com.enth.ecomusic.model.enums.RoleType
    '!gen_java com.enth.ecomusic.model.enums.VisibilityType
}

' --- Relationships ---


@enduml